"""
This script runs the DustFlight_Dragon application using a development server.
"""

from os import environ
from main import app


def start_application():
    run_server()
    print("[NOTICE] Running Function => [run_server]")


@app.route("/default")
def default():
    return "<h1>This Project Generated By DustFlight Visual Studio !</h1>"


def run_server():
    HOST = environ.get('SERVER_HOST', 'localhost')
    try:
        PORT = int(environ.get('SERVER_PORT', '5555'))
    except ValueError:
        PORT = 5555
    app.run(HOST, PORT)


def main():
    print("=========================================================")
    start_application()
    print("=========================================================")


if __name__ == '__main__':
    main()

